apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: suricata
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-net1
  labels:
    k8s-app: suricata-sensor
spec:
  selector:
    matchLabels:
      name: suricata-sensor
  template:
    metadata:
      labels:
        name: suricata-sensor
    spec:
      tolerations:
      # this toleration is to have the daemonset runnable on master nodes
      # remove it if your masters can't run pods
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: external-suricata-1
        image: jasonish/suricata:5.0.3
        command: ["/usr/bin/suricata"]
        args: ["-i", "net1"]
        resources:
          limits:
            cpu: 2
            memory: 4G
        volumeMounts:
        - name: suricatalogs-1
          mountPath: /var/log/suricata
        - name: suricataruntimedata-1
          mountPath: /var/lib/suricata
        - name: suricataconfigurations-1
          mountPath: /etc/suricata
        resources:
          requests:
            intel.com/intel_sriov_netdevice: '1'
          limits:
            intel.com/intel_sriov_netdevice: '1'
      - name: external-suricata-2
        image: jasonish/suricata:5.0.3
        command: ["/usr/bin/suricata"]
        args: ["-i", "net1"]
        resources:
          limits:
            cpu: 2
            memory: 4G
        volumeMounts:
        - name: suricatalogs-2
          mountPath: /var/log/suricata
        - name: suricataruntimedata-2
          mountPath: /var/lib/suricata
        - name: suricataconfigurations-2
          mountPath: /etc/suricata
        resources:
          requests:
            intel.com/intel_sriov_netdevice: '1'
          limits:
            intel.com/intel_sriov_netdevice: '1'
      - name: external-suricata-3
        image: jasonish/suricata:5.0.3
        command: ["/usr/bin/suricata"]
        args: ["-i", "net1"]
        resources:
          limits:
            cpu: 2
            memory: 4G
        volumeMounts:
        - name: suricatalogs-3
          mountPath: /var/log/suricata
        - name: suricataruntimedata-3
          mountPath: /var/lib/suricata
        - name: suricataconfigurations-3
          mountPath: /etc/suricata
        resources:
          requests:
            intel.com/intel_sriov_netdevice: '1'
          limits:
            intel.com/intel_sriov_netdevice: '1'
      - name: external-suricata-4
        image: jasonish/suricata:5.0.3
        command: ["/usr/bin/suricata"]
        args: ["-i", "net1"]
        resources:
          limits:
            cpu: 2
            memory: 4G
        volumeMounts:
        - name: suricatalogs-4
          mountPath: /var/log/suricata
        - name: suricataruntimedata-4
          mountPath: /var/lib/suricata
        - name: suricataconfigurations-4
          mountPath: /etc/suricata
        resources:
          requests:
            intel.com/intel_sriov_netdevice: '1'
          limits:
            intel.com/intel_sriov_netdevice: '1'
      - name: external-suricata-5
        image: jasonish/suricata:5.0.3
        command: ["/usr/bin/suricata"]
        args: ["-i", "net1"]
        resources:
          limits:
            cpu: 2
            memory: 4G
        volumeMounts:
        - name: suricatalogs-5
          mountPath: /var/log/suricata
        - name: suricataruntimedata-5
          mountPath: /var/lib/suricata
        - name: suricataconfigurations-5
          mountPath: /etc/suricata
        resources:
          requests:
            intel.com/intel_sriov_netdevice: '1'
          limits:
            intel.com/intel_sriov_netdevice: '1'
      terminationGracePeriodSeconds: 30
      volumes:
      - name: suricatalogs-1
        hostPath:
          path: /data/suricata1/logs
      - name: suricataruntimedata-1
        hostPath:
          path: /data/suricata1/runtime
      - name: suricataconfigurations-1
        hostPath:
          path: /data/suricata1/confs
      - name: suricatalogs-2
        hostPath:
          path: /data/suricata2/logs
      - name: suricataruntimedata-2
        hostPath:
          path: /data/suricata2/runtime
      - name: suricataconfigurations-2
        hostPath:
          path: /data/suricata2/confs
      - name: suricatalogs-3
        hostPath:
          path: /data/suricata3/logs
      - name: suricataruntimedata-3
        hostPath:
          path: /data/suricata3/runtime
      - name: suricataconfigurations-3
        hostPath:
          path: /data/suricata3/confs
      - name: suricatalogs-4
        hostPath:
          path: /data/suricata4/logs
      - name: suricataruntimedata-4
        hostPath:
          path: /data/suricata4/runtime
      - name: suricataconfigurations-4
        hostPath:
          path: /data/suricata4/confs
      - name: suricatalogs-5
        hostPath:
          path: /data/suricata5/logs
      - name: suricataruntimedata-5
        hostPath:
          path: /data/suricata5/runtime
      - name: suricataconfigurations-5
        hostPath:
          path: /data/suricata5/confs
